# Generated by Django 4.2.2 on 2023-07-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='trans_type',
            new_name='action_type',
        ),
    ]
